### ISSUE TITLE
wp-gears-runner.php fails to open autoload.php

### ISSUE THREAD

**Issue by soderlind** [10up/WP-Minions#10]
Installed WP-Gears and copied wp-gears-runner.php to wp root.

wp-gears-runner.php [points to autoload.php](https://github.com/10up/WP-Gears/blob/master/wp-gears-runner.php#L11) in the same directory as it self.

If I change this to `require_once __DIR__ . '/wp-content/plugins/WP-Gears/autoload.php';` it works fine.

**Comment by dsawardekar** [comment]
@soderlind Good catch. We are using a symlink instead of copying the wp-gears-runner. That doesn't error since it's running from the plugin's directory.

I'll add a PR to support both symlinking and copying.

**Comment by dsawardekar** [comment]
This is fixed in the PR #11. However I think we ought to recommend the symlink approach over copying. It allows for future upgrades to be made to WP-Gears without needing to overwrite the copied file.

**Comment by cmmarslender** [comment]
@dsawardekar I agree on the symlink being the better option - We do start this in the readme:

> Create a symlink at the site root (the same directory as wp-settings.php) that points to the wp-gears-runner.php file in the plugin (or copy the file, but a symlink will ensure it is updated if the plugin is updated)

Could possibly be worded a bit differently to more obviously prefer a symlink.
