### ISSUE TITLE
$args not being passed into callback function

### ISSUE THREAD

**Issue by zachtownsend** [10up/WP-Minions#25]
Hi, I've copied and pasted the example into functions.php to see if it works, and the $args passed into the callback function are not working. Any ideas why this might be happening?

Thanks,
Zach

**Comment by cmmarslender** [comment]
I just tested this on a fresh environment, and the example in the readme works for me. Can you provide any more information about the environment you are running this in that might help to diagnose the problem?

**Comment by zachtownsend** [comment]
So actually I'm using Roots Sage/Bedrock setup so not quite a typical WordPress setup. It's running on a server running CentOS with PHP5.6.

**Comment by cmmarslender** [comment]
There was a bug with the args in the wp cron fallback that was resolved in #32 
Do you still see this after that was merged?
